### ISSUE TITLE
KeyGen Topic almost done!

### ISSUE THREAD

**Issue by sgharms** [audibleblink/cryptoparty#7]
FYI: I'm almost done with the key-gen topic. From there it should be pretty easy to get the work done on the encrypt / decrypt. I'm providing a modified writeup of:

https://alexcabal.com/creating-the-perfect-gpg-keypair/

**Comment by audibleblink** [comment]
👍  I loved that one.

Specifically on the subkey use

**Comment by sgharms** [comment]
I've been messing with it a lot this last month trying to figure out the
steps it's just recently become clear to me.

I have an update to do because I have a few facts wrong. But close.
